feat: H2のバージョンを 2.1.214 に更新しました。
nablarch/nablarch-example-mom-delayed-receive pull request #27
Opened 2022-10-21 05:36 UTC by sukegawatakashitis

jiraチケット
https://nablarch.atlassian.net/browse/NAB-468

2022-10-25 01:23 UTC, kumagoro1202 commented
登録リクエストIDの対応で、問題は古いバージョンのH2ではCHAR(固定長文字列)にも関わらずアサートする際に取得される値がトリムされた状態になっているが、新しいバージョンではトリムされず定義の通り固定長の値が取得されるということだと思います。
この対応としてテーブル定義の文字数を少なくしてトリムされない文字数にしていますが、本質的な対応ではなく場当たり的な対応だと思います。たまたま現在入力値となっているProjectInsertMessageが20文字だから20文字に変更していますが、文字数が21や22だったらCHAR(21)というような定義に変更することになります。
リクエストIDは固定長の文字列ではないのに定義がCHARになっているのが根本原因だと思います。VARCHARにするか、期待値をスペース埋めした固定長の文字列としてください。

2022-10-25 01:24 UTC, kumagoro1202 requested changes

2022-10-25 01:24 UTC, kumagoro1202 commented on src/main/resources/entity/data-model.edm
> +    <ATTR ID="401" L-NAME="登録リクエストID" P-NAME="INSERT_REQUEST_ID" DDOMAINID="0" DATATYPE="CHAR" LENGTH="20" SCALE="0" NULL="0" DEFID="0" DEF="" RULEID="0" RULE="" CODEDEFINEID="0" COMMENT="" COLLATE="
登録リクエストIDの対応で、問題は古いバージョンのH2ではCHAR(固定長文字列)にも関わらずアサートする際に取得される値がトリムされた状態になっているが、新しいバージョンではトリムされず定義の通り固定長の値が取得されるということだと思います。
この対応としてテーブル定義の文字数を少なくしてトリムされない文字数にしていますが、本質的な対応ではなく場当たり的な対応だと思います。たまたま現在入力値となっているProjectInsertMessageが20文字だから20文字に変更していますが、文字数が21や22だったらCHAR(21)というような定義に変更することになります。
リクエストIDは固定長の文字列ではないのに定義がCHARになっているのが根本原因だと思います。VARCHARにするか、期待値をスペース埋めした固定長の文字列としてください。

2022-10-27 04:06 UTC, sukegawatakashitis commented on src/main/resources/entity/data-model.edm
> +    <ATTR ID="401" L-NAME="登録リクエストID" P-NAME="INSERT_REQUEST_ID" DDOMAINID="0" DATATYPE="CHAR" LENGTH="20" SCALE="0" NULL="0" DEFID="0" DEF="" RULEID="0" RULE="" CODEDEFINEID="0" COMMENT="" COLLATE="
こちらで対応しました。
https://github.com/nablarch/nablarch-example-mom-delayed-receive/pull/27/commits/aa85d0c0739dbaa017e39f927da4332999ad61b9

2022-11-07 04:54 UTC, kumagoro1202 approved these changes

2022-11-07 04:54 UTC, merged